name: jum
favicon: null
layout_spectrum: 0.005585486069321632
typography_spectrum: 0.9407074514310807
title: Live Together. Live Strong.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cbced7'
    - '#5b677d'
    - '#798194'
    - '#000000'
    - '#3f0000'
  brandStrength: 0.4375
  lightness: 0.10548357455991209
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
